server:
  port: 8080


#AI大模型配置项(Qwen)
qwen-model:
  api-key: "sk-aa68faaa357b41ab8eeeb91cc7556165"
  model-name: "qwen-max" # 可换为 qwen-plus、qwen-turbo
  embedding-model: "text-embedding-v4"

#spring-ai 本地模型
ollama:
  base-url: http://localhost:11434
  model-name: qwen2.5:7b

# 向量数据库配置
rag:
  pgvector:
    table: gov_embeddings

#本地向量模型
embedding:
  model:
    path: D:\web3-java\ai-guidance-server\src\main\resources\models\model.onnx
    tokenizer-path: D:\web3-java\ai-guidance-server\src\main\resources\models\tokenizer.json

spring:
  datasource:
    # 数据库连接 URL (注意库名，这里假设是 postgres)
    url: jdbc:postgresql://localhost:5431/postgres
    username: postgres
    password: 123456
    #password: postgres
    driver-class-name: org.postgresql.Driver

    # HikariCP 连接池配置 (生产环境推荐优化)
    hikari:
      minimum-idle: 5        # 最小空闲连接数
      maximum-pool-size: 20  # 最大连接数
      idle-timeout: 30000    # 空闲超时时间
      pool-name: GovRagCP    # 连接池名称
      max-lifetime: 1800000  # 连接最大存活时间

debug: false

#爬虫是否开启
crawl:
  #区域信息爬虫
  area:
    enable: false
  #指南信息爬虫
  guide:
    enable: false
